# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'b:\APPLICACION\flycast-feature-model\FlyCast\src\gui_ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 552)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setStyleSheet("Qframe{\n"
"border-radius: 10px;\n"
"background-image: url(images\\plane-vertical.jpg);\n"
"}")
        self.frame.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.frame.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("QPushButton{\n"
"border-radius:18px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.frame_superior.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.frame_superior.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(443, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem)
        self.bt_minimize = QtWidgets.QPushButton(self.frame_superior)
        self.bt_minimize.setMinimumSize(QtCore.QSize(38, 38))
        self.bt_minimize.setMaximumSize(QtCore.QSize(38, 38))
        self.bt_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("b:\\APPLICACION\\flycast-feature-model\\FlyCast\\src\\gui_ui\\icons/1x/hideAsset 53.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimize.setIcon(icon)
        self.bt_minimize.setIconSize(QtCore.QSize(38, 38))
        self.bt_minimize.setObjectName("bt_minimize")
        self.horizontalLayout_3.addWidget(self.bt_minimize)
        self.bt_maximize = QtWidgets.QPushButton(self.frame_superior)
        self.bt_maximize.setMinimumSize(QtCore.QSize(38, 38))
        self.bt_maximize.setMaximumSize(QtCore.QSize(38, 38))
        self.bt_maximize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("b:\\APPLICACION\\flycast-feature-model\\FlyCast\\src\\gui_ui\\icons/1x/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maximize.setIcon(icon1)
        self.bt_maximize.setIconSize(QtCore.QSize(38, 38))
        self.bt_maximize.setObjectName("bt_maximize")
        self.horizontalLayout_3.addWidget(self.bt_maximize)
        self.bt_normal = QtWidgets.QPushButton(self.frame_superior)
        self.bt_normal.setMinimumSize(QtCore.QSize(38, 38))
        self.bt_normal.setMaximumSize(QtCore.QSize(38, 38))
        self.bt_normal.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("b:\\APPLICACION\\flycast-feature-model\\FlyCast\\src\\gui_ui\\icons/1x/restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_normal.setIcon(icon2)
        self.bt_normal.setIconSize(QtCore.QSize(38, 38))
        self.bt_normal.setObjectName("bt_normal")
        self.horizontalLayout_3.addWidget(self.bt_normal)
        self.bt_close = QtWidgets.QPushButton(self.frame_superior)
        self.bt_close.setMinimumSize(QtCore.QSize(38, 38))
        self.bt_close.setMaximumSize(QtCore.QSize(38, 38))
        self.bt_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("b:\\APPLICACION\\flycast-feature-model\\FlyCast\\src\\gui_ui\\icons/1x/closeAsset 43.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_close.setIcon(icon3)
        self.bt_close.setIconSize(QtCore.QSize(38, 38))
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout_3.addWidget(self.bt_close)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("Qframe{\n"
"border-radius:10px;\n"
"background-image:url(images/plane-vertical.jpg);}")
        self.frame_3.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.frame_3.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(28, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(400, 600))
        self.frame_4.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 254);\n"
"    font: 12pt \"Arial\";\n"
"    background-color: rgba(0, 0, 0,0);\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"background-color: rgba(0, 0, 0,0);\n"
"border-radius:10px; \n"
"font: 12pt \"Arial\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid  rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgba(0, 0, 0,0);\n"
"border-radius:10px; \n"
"font: 12pt \"Arial\";\n"
"border: 2px solid  rgb(120, 0, 171);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius:10px; \n"
"font: 12pt \"Arial\";\n"
"border: 2px solid rgb(120, 0, 171);\n"
"}\n"
"\n"
"QCheckBox{\n"
"    font: 12pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height:18px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"   background-image: url(image/square.svg);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"   background-image: url(image/check-square.svg);\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius:10px; \n"
"font: 12pt \"Arial\";\n"
"color: rgb(255, 255, 254);\n"
"border: 2px solid #ffffff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius:10px; \n"
"font: 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(120, 0, 171);\n"
"    background-color: rgb(120, 0, 171);\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.frame_4.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("font: 16pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.lineEdit1 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit1.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit1.setObjectName("lineEdit1")
        self.verticalLayout_3.addWidget(self.lineEdit1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.lineEdit2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit2.setEchoMode(QtCore.Qt.QLineEdit::EchoMode::Password)
        self.lineEdit2.setObjectName("lineEdit2")
        self.verticalLayout_3.addWidget(self.lineEdit2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.checkBox = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("b:\\APPLICACION\\flycast-feature-model\\FlyCast\\src\\gui_ui\\images/facebook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("b:\\APPLICACION\\flycast-feature-model\\FlyCast\\src\\gui_ui\\images/google.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border-radius:10px; \n"
"font: 12pt \"Arial\";\n"
"color: rgb(255, 255, 254);\n"
"border: None;\n"
"background-color: None;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius:10px; \n"
"font: 12pt \"Arial\";\n"
"color: rgb(117, 0, 175);\n"
"border: None;\n"
"background-color: None;\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.frame_4)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        spacerItem11 = QtWidgets.QSpacerItem(177, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Iniciar Aplicación"))
        self.checkBox.setText(_translate("MainWindow", "Recordar contraseña"))
        self.pushButton.setText(_translate("MainWindow", "Iniciar Sesión"))
        self.pushButton_2.setText(_translate("MainWindow", "Facebook"))
        self.pushButton_3.setText(_translate("MainWindow", "Google"))
        self.label_2.setText(_translate("MainWindow", "¿No tienes una cuenta? "))
        self.pushButton_4.setText(_translate("MainWindow", "Inscribete"))
